<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['name' => ['en' => 'US Dollar', 'ar' => 'الدولار الأمريكي'], 'code' => 'USD', 'symbol' => '$', 'description' => ['en' => 'United States Dollar', 'ar' => 'الدولار الأمريكي'], 'is_default' => true],
            ['name' => ['en' => 'Euro', 'ar' => 'اليورو'], 'code' => 'EUR', 'symbol' => '€', 'description' => ['en' => 'Euro', 'ar' => 'اليورو'], 'is_default' => false],
            ['name' => ['en' => 'British Pound', 'ar' => 'الجنيه الإسترليني'], 'code' => 'GBP', 'symbol' => '£', 'description' => ['en' => 'British Pound Sterling', 'ar' => 'الجنيه الإسترليني'], 'is_default' => false],
            ['name' => ['en' => 'Japanese Yen', 'ar' => 'الين الياباني'], 'code' => 'JPY', 'symbol' => '¥', 'description' => ['en' => 'Japanese Yen', 'ar' => 'الين الياباني'], 'is_default' => false],
            ['name' => ['en' => 'Canadian Dollar', 'ar' => 'الدولار الكندي'], 'code' => 'CAD', 'symbol' => 'C$', 'description' => ['en' => 'Canadian Dollar', 'ar' => 'الدولار الكندي'], 'is_default' => false],
            ['name' => ['en' => 'Australian Dollar', 'ar' => 'الدولار الأسترالي'], 'code' => 'AUD', 'symbol' => 'A$', 'description' => ['en' => 'Australian Dollar', 'ar' => 'الدولار الأسترالي'], 'is_default' => false],
            ['name' => ['en' => 'Swiss Franc', 'ar' => 'الفرنك السويسري'], 'code' => 'CHF', 'symbol' => 'CHF', 'description' => ['en' => 'Swiss Franc', 'ar' => 'الفرنك السويسري'], 'is_default' => false],
            ['name' => ['en' => 'Chinese Yuan', 'ar' => 'اليوان الصيني'], 'code' => 'CNY', 'symbol' => '¥', 'description' => ['en' => 'Chinese Yuan', 'ar' => 'اليوان الصيني'], 'is_default' => false],
            ['name' => ['en' => 'Swedish Krona', 'ar' => 'الكرونا السويدية'], 'code' => 'SEK', 'symbol' => 'kr', 'description' => ['en' => 'Swedish Krona', 'ar' => 'الكرونا السويدية'], 'is_default' => false],
            ['name' => ['en' => 'New Zealand Dollar', 'ar' => 'الدولار النيوزيلندي'], 'code' => 'NZD', 'symbol' => 'NZ$', 'description' => ['en' => 'New Zealand Dollar', 'ar' => 'الدولار النيوزيلندي'], 'is_default' => false],
            ['name' => ['en' => 'Mexican Peso', 'ar' => 'البيزو المكسيكي'], 'code' => 'MXN', 'symbol' => '$', 'description' => ['en' => 'Mexican Peso', 'ar' => 'البيزو المكسيكي'], 'is_default' => false],
            ['name' => ['en' => 'Singapore Dollar', 'ar' => 'الدولار السنغافوري'], 'code' => 'SGD', 'symbol' => 'S$', 'description' => ['en' => 'Singapore Dollar', 'ar' => 'الدولار السنغافوري'], 'is_default' => false],
            ['name' => ['en' => 'Hong Kong Dollar', 'ar' => 'الدولار Hong Kong'], 'code' => 'HKD', 'symbol' => 'HK$', 'description' => ['en' => 'Hong Kong Dollar', 'ar' => 'الدولار Hong Kong'], 'is_default' => false],
            ['name' => ['en' => 'Norwegian Krone', 'ar' => 'الكرونا النرويجية'], 'code' => 'NOK', 'symbol' => 'kr', 'description' => ['en' => 'Norwegian Krone', 'ar' => 'الكرونا النرويجية'], 'is_default' => false],
            ['name' => ['en' => 'South Korean Won', 'ar' => 'الوون الكوري الجنوبي'], 'code' => 'KRW', 'symbol' => '₩', 'description' => ['en' => 'South Korean Won', 'ar' => 'الوون الكوري الجنوبي'], 'is_default' => false],
            ['name' => ['en' => 'Turkish Lira', 'ar' => 'الليرة التركية'], 'code' => 'TRY', 'symbol' => '₺', 'description' => ['en' => 'Turkish Lira', 'ar' => 'الليرة التركية'], 'is_default' => false],
            ['name' => ['en' => 'Russian Ruble', 'ar' => 'الروبل الروسي'], 'code' => 'RUB', 'symbol' => '₽', 'description' => ['en' => 'Russian Ruble', 'ar' => 'الروبل الروسي'], 'is_default' => false],
            ['name' => ['en' => 'Indian Rupee', 'ar' => 'الروبية الهندية'], 'code' => 'INR', 'symbol' => '₹', 'description' => ['en' => 'Indian Rupee', 'ar' => 'الروبية الهندية'], 'is_default' => false],
            ['name' => ['en' => 'Brazilian Real', 'ar' => 'الريال البرازيلي'], 'code' => 'BRL', 'symbol' => 'R$', 'description' => ['en' => 'Brazilian Real', 'ar' => 'الريال البرازيلي'], 'is_default' => false],
            ['name' => ['en' => 'South African Rand', 'ar' => 'الراند الجنوب أفريقي'], 'code' => 'ZAR', 'symbol' => 'R', 'description' => ['en' => 'South African Rand', 'ar' => 'الراند الجنوب أفريقي'], 'is_default' => false],
            ['name' => ['en' => 'Polish Zloty', 'ar' => 'الزلوتي البولندي'], 'code' => 'PLN', 'symbol' => 'zł', 'description' => ['en' => 'Polish Zloty', 'ar' => 'الزلوتي البولندي'], 'is_default' => false],
            ['name' => ['en' => 'Israeli Shekel', 'ar' => 'الشيكل الإسرائيلي'], 'code' => 'ILS', 'symbol' => '₪', 'description' => ['en' => 'Israeli Shekel', 'ar' => 'الشيكل الإسرائيلي'], 'is_default' => false],
            ['name' => ['en' => 'Danish Krone', 'ar' => 'الكرونا الدنماركية'], 'code' => 'DKK', 'symbol' => 'kr', 'description' => ['en' => 'Danish Krone', 'ar' => 'الكرونا الدنماركية'], 'is_default' => false],
            ['name' => ['en' => 'Czech Koruna', 'ar' => 'الكرونا التشيكية'], 'code' => 'CZK', 'symbol' => 'Kč', 'description' => ['en' => 'Czech Koruna', 'ar' => 'الكرونا التشيكية'], 'is_default' => false],
            ['name' => ['en' => 'Hungarian Forint', 'ar' => 'الفورنت المجري'], 'code' => 'HUF', 'symbol' => 'Ft', 'description' => ['en' => 'Hungarian Forint', 'ar' => 'الفورنت المجري'], 'is_default' => false],
            ['name' => ['en' => 'Romanian Leu', 'ar' => 'الليو الروماني'], 'code' => 'RON', 'symbol' => 'lei', 'description' => ['en' => 'Romanian Leu', 'ar' => 'الليو الروماني'], 'is_default' => false],
            ['name' => ['en' => 'Croatian Kuna', 'ar' => 'الكونا الكرواتية'], 'code' => 'HRK', 'symbol' => 'kn', 'description' => ['en' => 'Croatian Kuna', 'ar' => 'الكونا الكرواتية'], 'is_default' => false],
            ['name' => ['en' => 'Bulgarian Lev', 'ar' => 'الليف البلغاري'], 'code' => 'BGN', 'symbol' => 'лв', 'description' => ['en' => 'Bulgarian Lev', 'ar' => 'الليف البلغاري'], 'is_default' => false],
            ['name' => ['en' => 'Thai Baht', 'ar' => 'الباهت التايلاندي'], 'code' => 'THB', 'symbol' => '฿', 'description' => ['en' => 'Thai Baht', 'ar' => 'الباهت التايلاندي'], 'is_default' => false],
            ['name' => ['en' => 'Malaysian Ringgit', 'ar' => 'الرينغيت الماليزي'], 'code' => 'MYR', 'symbol' => 'RM', 'description' => ['en' => 'Malaysian Ringgit', 'ar' => 'الرينغيت الماليزي'], 'is_default' => false],
            ['name' => ['en' => 'Indonesian Rupiah', 'ar' => 'الروبية الإندونيسية'], 'code' => 'IDR', 'symbol' => 'Rp', 'description' => ['en' => 'Indonesian Rupiah', 'ar' => 'الروبية الإندونيسية'], 'is_default' => false],
            ['name' => ['en' => 'Philippine Peso', 'ar' => 'البيزو الفلبيني'], 'code' => 'PHP', 'symbol' => '₱', 'description' => ['en' => 'Philippine Peso', 'ar' => 'البيزو الفلبيني'], 'is_default' => false],
            ['name' => ['en' => 'Vietnamese Dong', 'ar' => 'الدونغ الفيتنامي'], 'code' => 'VND', 'symbol' => '₫', 'description' => ['en' => 'Vietnamese Dong', 'ar' => 'الدونغ الفيتنامي'], 'is_default' => false],
            ['name' => ['en' => 'Argentine Peso', 'ar' => 'البيزو الأرجنتيني'], 'code' => 'ARS', 'symbol' => '$', 'description' => ['en' => 'Argentine Peso', 'ar' => 'البيزو الأرجنتيني'], 'is_default' => false],
            ['name' => ['en' => 'Chilean Peso', 'ar' => 'البيزو التشيلي'], 'code' => 'CLP', 'symbol' => '$', 'description' => ['en' => 'Chilean Peso', 'ar' => 'البيزو التشيلي'], 'is_default' => false],
            ['name' => ['en' => 'Colombian Peso', 'ar' => 'البيزو الكولومبي'], 'code' => 'COP', 'symbol' => '$', 'description' => ['en' => 'Colombian Peso', 'ar' => 'البيزو الكولومبي'], 'is_default' => false],
            ['name' => ['en' => 'Peruvian Sol', 'ar' => 'السول البيروفي'], 'code' => 'PEN', 'symbol' => 'S/', 'description' => ['en' => 'Peruvian Sol', 'ar' => 'السول البيروفي'], 'is_default' => false],
            ['name' => ['en' => 'Uruguayan Peso', 'ar' => 'البيزو الأوروغواياني'], 'code' => 'UYU', 'symbol' => '$U', 'description' => ['en' => 'Uruguayan Peso', 'ar' => 'البيزو الأوروغواياني'], 'is_default' => false],
            ['name' => ['en' => 'Egyptian Pound', 'ar' => 'الجنيه المصري'], 'code' => 'EGP', 'symbol' => '£', 'description' => ['en' => 'Egyptian Pound', 'ar' => 'الجنيه المصري'], 'is_default' => false],
            ['name' => ['en' => 'Nigerian Naira', 'ar' => 'النيرة النيجيرية'], 'code' => 'NGN', 'symbol' => '₦', 'description' => ['en' => 'Nigerian Naira', 'ar' => 'النيرة النيجيرية'], 'is_default' => false],
            ['name' => ['en' => 'Kenyan Shilling', 'ar' => 'الشلن الكيني'], 'code' => 'KES', 'symbol' => 'KSh', 'description' => ['en' => 'Kenyan Shilling', 'ar' => 'الشلن الكيني'], 'is_default' => false],
            ['name' => ['en' => 'Moroccan Dirham', 'ar' => 'الدرهم المغربي'], 'code' => 'MAD', 'symbol' => 'DH', 'description' => ['en' => 'Moroccan Dirham', 'ar' => 'الدرهم المغربي'], 'is_default' => false],
            ['name' => ['en' => 'Tunisian Dinar', 'ar' => 'الدينار التونسي'], 'code' => 'TND', 'symbol' => 'د.ت', 'description' => ['en' => 'Tunisian Dinar', 'ar' => 'الدينار التونسي'], 'is_default' => false],
            ['name' => ['en' => 'UAE Dirham', 'ar' => 'الدرهم الإماراتي'], 'code' => 'AED', 'symbol' => 'د.إ', 'description' => ['en' => 'UAE Dirham', 'ar' => 'الدرهم الإماراتي'], 'is_default' => false],
            ['name' => ['en' => 'Saudi Riyal', 'ar' => 'الريال السعودي'], 'code' => 'SAR', 'symbol' => '﷼', 'description' => ['en' => 'Saudi Riyal', 'ar' => 'الريال السعودي'], 'is_default' => false],
            ['name' => ['en' => 'Qatari Riyal', 'ar' => 'الريال القطري'], 'code' => 'QAR', 'symbol' => '﷼', 'description' => ['en' => 'Qatari Riyal', 'ar' => 'الريال القطري'], 'is_default' => false],
            ['name' => ['en' => 'Kuwaiti Dinar', 'ar' => 'الدينار الكويتي'], 'code' => 'KWD', 'symbol' => 'د.ك', 'description' => ['en' => 'Kuwaiti Dinar', 'ar' => 'الدينار الكويتي'], 'is_default' => false],
            ['name' => ['en' => 'Bahraini Dinar', 'ar' => 'الدينار البحريني'], 'code' => 'BHD', 'symbol' => '.د.ب', 'description' => ['en' => 'Bahraini Dinar', 'ar' => 'الدينار البحريني'], 'is_default' => false],
            ['name' => ['en' => 'Omani Rial', 'ar' => 'الريال العماني'], 'code' => 'OMR', 'symbol' => '﷼', 'description' => ['en' => 'Omani Rial', 'ar' => 'الريال العماني'], 'is_default' => false],
            ['name' => ['en' => 'Jordanian Dinar', 'ar' => 'الدينار الأردني'], 'code' => 'JOD', 'symbol' => 'د.ا', 'description' => ['en' => 'Jordanian Dinar', 'ar' => 'الدينار الأردني'], 'is_default' => false],
            ['name' => ['en' => 'Lebanese Pound', 'ar' => 'الليرة اللبنانية'], 'code' => 'LBP', 'symbol' => '£', 'description' => ['en' => 'Lebanese Pound', 'ar' => 'الليرة اللبنانية'], 'is_default' => false],
            ['name' => ['en' => 'Pakistani Rupee', 'ar' => 'الروبية الباكستانية'], 'code' => 'PKR', 'symbol' => '₨', 'description' => ['en' => 'Pakistani Rupee', 'ar' => 'الروبية الباكستانية'], 'is_default' => false],
            ['name' => ['en' => 'Bangladeshi Taka', 'ar' => 'التاكا البنغلاديشي'], 'code' => 'BDT', 'symbol' => '৳', 'description' => ['en' => 'Bangladeshi Taka', 'ar' => 'التاكا البنغلاديشي'], 'is_default' => false],
            ['name' => ['en' => 'Sri Lankan Rupee', 'ar' => 'الروبية السريلانكية'], 'code' => 'LKR', 'symbol' => '₨', 'description' => ['en' => 'Sri Lankan Rupee', 'ar' => 'الروبية السريلانكية'], 'is_default' => false],
            ['name' => ['en' => 'Nepalese Rupee', 'ar' => 'الروبية النيبالية'], 'code' => 'NPR', 'symbol' => '₨', 'description' => ['en' => 'Nepalese Rupee', 'ar' => 'الروبية النيبالية'], 'is_default' => false],
            ['name' => ['en' => 'Myanmar Kyat', 'ar' => 'الكيات الميانماري'], 'code' => 'MMK', 'symbol' => 'K', 'description' => ['en' => 'Myanmar Kyat', 'ar' => 'الكيات الميانماري'], 'is_default' => false],
            ['name' => ['en' => 'Cambodian Riel', 'ar' => 'الرييل الكمبودي'], 'code' => 'KHR', 'symbol' => '៛', 'description' => ['en' => 'Cambodian Riel', 'ar' => 'الرييل الكمبودي'], 'is_default' => false],
            ['name' => ['en' => 'Laotian Kip', 'ar' => 'الكيب اللاوسي'], 'code' => 'LAK', 'symbol' => '₭', 'description' => ['en' => 'Laotian Kip', 'ar' => 'الكيب اللاوسي'], 'is_default' => false],
            ['name' => ['en' => 'Mongolian Tugrik', 'ar' => 'التوغريك المنغولي'], 'code' => 'MNT', 'symbol' => '₮', 'description' => ['en' => 'Mongolian Tugrik', 'ar' => 'التوغريك المنغولي'], 'is_default' => false],
            ['name' => ['en' => 'Kazakhstani Tenge', 'ar' => 'التنغي الكازاخستاني'], 'code' => 'KZT', 'symbol' => '₸', 'description' => ['en' => 'Kazakhstani Tenge', 'ar' => 'التنغي الكازاخستاني'], 'is_default' => false],
            ['name' => ['en' => 'Uzbekistani Som', 'ar' => 'السوم الأوزبكستاني'], 'code' => 'UZS', 'symbol' => 'лв', 'description' => ['en' => 'Uzbekistani Som', 'ar' => 'السوم الأوزبكستاني'], 'is_default' => false],
            ['name' => ['en' => 'Ukrainian Hryvnia', 'ar' => 'الهريفنيا الأوكرانية'], 'code' => 'UAH', 'symbol' => '₴', 'description' => ['en' => 'Ukrainian Hryvnia', 'ar' => 'الهريفنيا الأوكرانية'], 'is_default' => false],
            ['name' => ['en' => 'Belarusian Ruble', 'ar' => 'الروبل البيلاروسي'], 'code' => 'BYN', 'symbol' => 'Br', 'description' => ['en' => 'Belarusian Ruble', 'ar' => 'الروبل البيلاروسي'], 'is_default' => false],
            ['name' => ['en' => 'Moldovan Leu', 'ar' => 'الليو المولدوفي'], 'code' => 'MDL', 'symbol' => 'L', 'description' => ['en' => 'Moldovan Leu', 'ar' => 'الليو المولدوفي'], 'is_default' => false],
            ['name' => ['en' => 'Georgian Lari', 'ar' => 'اللاري الجورجي'], 'code' => 'GEL', 'symbol' => '₾', 'description' => ['en' => 'Georgian Lari', 'ar' => 'اللاري الجورجي'], 'is_default' => false],
            ['name' => ['en' => 'Armenian Dram', 'ar' => 'الدرام الأرمني'], 'code' => 'AMD', 'symbol' => '֏', 'description' => ['en' => 'Armenian Dram', 'ar' => 'الدرام الأرمني'], 'is_default' => false],
            ['name' => ['en' => 'Azerbaijani Manat', 'ar' => 'المانات الأذربيجاني'], 'code' => 'AZN', 'symbol' => '₼', 'description' => ['en' => 'Azerbaijani Manat', 'ar' => 'المانات الأذربيجاني'], 'is_default' => false],
            ['name' => ['en' => 'Icelandic Krona', 'ar' => 'الكرونا الآيسلندية'], 'code' => 'ISK', 'symbol' => 'kr', 'description' => ['en' => 'Icelandic Krona', 'ar' => 'الكرونا الآيسلندية'], 'is_default' => false],
            ['name' => ['en' => 'Albanian Lek', 'ar' => 'الليك الألباني'], 'code' => 'ALL', 'symbol' => 'L', 'description' => ['en' => 'Albanian Lek', 'ar' => 'الليك الألباني'], 'is_default' => false],
            ['name' => ['en' => 'Serbian Dinar', 'ar' => 'الدينار الصربي'], 'code' => 'RSD', 'symbol' => 'дин', 'description' => ['en' => 'Serbian Dinar', 'ar' => 'الدينار الصربي'], 'is_default' => false],
            ['name' => ['en' => 'Bosnian Mark', 'ar' => 'المارك البوسني'], 'code' => 'BAM', 'symbol' => 'KM', 'description' => ['en' => 'Bosnian Mark', 'ar' => 'المارك البوسني'], 'is_default' => false],
            ['name' => ['en' => 'North Macedonian Denar', 'ar' => 'الدينار المقدوني الشمالي'], 'code' => 'MKD', 'symbol' => 'ден', 'description' => ['en' => 'North Macedonian Denar', 'ar' => 'الدينار المقدوني الشمالي'], 'is_default' => false],
            ['name' => ['en' => 'Ethiopian Birr', 'ar' => 'البر الإثيوبي'], 'code' => 'ETB', 'symbol' => 'Br', 'description' => ['en' => 'Ethiopian Birr', 'ar' => 'البر الإثيوبي'], 'is_default' => false],
            ['name' => ['en' => 'Ghanaian Cedi', 'ar' => 'السيدي الغاني'], 'code' => 'GHS', 'symbol' => '₵', 'description' => ['en' => 'Ghanaian Cedi', 'ar' => 'السيدي الغاني'], 'is_default' => false],
            ['name' => ['en' => 'Tanzanian Shilling', 'ar' => 'الشلن التنزاني'], 'code' => 'TZS', 'symbol' => 'TSh', 'description' => ['en' => 'Tanzanian Shilling', 'ar' => 'الشلن التنزاني'], 'is_default' => false],
            ['name' => ['en' => 'Ugandan Shilling', 'ar' => 'الشلن الأوغندي'], 'code' => 'UGX', 'symbol' => 'USh', 'description' => ['en' => 'Ugandan Shilling', 'ar' => 'الشلن الأوغندي'], 'is_default' => false],
            ['name' => ['en' => 'Zambian Kwacha', 'ar' => 'الكواشا الزامبي'], 'code' => 'ZMW', 'symbol' => 'ZK', 'description' => ['en' => 'Zambian Kwacha', 'ar' => 'الكواشا الزامبي'], 'is_default' => false],
            ['name' => ['en' => 'Botswana Pula', 'ar' => 'البولا البوتسواني'], 'code' => 'BWP', 'symbol' => 'P', 'description' => ['en' => 'Botswana Pula', 'ar' => 'البولا البوتسواني'], 'is_default' => false],
            ['name' => ['en' => 'Namibian Dollar', 'ar' => 'الدولار الناميبي'], 'code' => 'NAD', 'symbol' => 'N$', 'description' => ['en' => 'Namibian Dollar', 'ar' => 'الدولار الناميبي'], 'is_default' => false],
            ['name' => ['en' => 'Mauritian Rupee', 'ar' => 'الروبية الموريشيوسية'], 'code' => 'MUR', 'symbol' => '₨', 'description' => ['en' => 'Mauritian Rupee', 'ar' => 'الروبية الموريشيوسية'], 'is_default' => false],
            ['name' => ['en' => 'Seychellois Rupee', 'ar' => 'الروبية السيشيلية'], 'code' => 'SCR', 'symbol' => '₨', 'description' => ['en' => 'Seychellois Rupee', 'ar' => 'الروبية السيشيلية'], 'is_default' => false],
            ['name' => ['en' => 'Maldivian Rufiyaa', 'ar' => 'الروفية المالديفية'], 'code' => 'MVR', 'symbol' => '.ރ', 'description' => ['en' => 'Maldivian Rufiyaa', 'ar' => 'الروفية المالديفية'], 'is_default' => false],
            ['name' => ['en' => 'Fijian Dollar', 'ar' => 'الدولار الفيجي'], 'code' => 'FJD', 'symbol' => 'FJ$', 'description' => ['en' => 'Fijian Dollar', 'ar' => 'الدولار الفيجي'], 'is_default' => false],
            ['name' => ['en' => 'Papua New Guinean Kina', 'ar' => 'الكينا البابوا غينيا الجديدة'], 'code' => 'PGK', 'symbol' => 'K', 'description' => ['en' => 'Papua New Guinean Kina', 'ar' => 'الكينا البابوا غينيا الجديدة'], 'is_default' => false],
            ['name' => ['en' => 'Tongan Paʻanga', 'ar' => 'البانغا التونغية'], 'code' => 'TOP', 'symbol' => 'T$', 'description' => ['en' => 'Tongan Paʻanga', 'ar' => 'البانغا التونغية'], 'is_default' => false],
            ['name' => ['en' => 'Samoan Tala', 'ar' => 'التالا الساموي'], 'code' => 'WST', 'symbol' => 'T', 'description' => ['en' => 'Samoan Tala', 'ar' => 'التالا الساموي'], 'is_default' => false],
            ['name' => ['en' => 'Vanuatu Vatu', 'ar' => 'الفاتو الفانواتي'], 'code' => 'VUV', 'symbol' => 'VT', 'description' => ['en' => 'Vanuatu Vatu', 'ar' => 'الفاتو الفانواتي'], 'is_default' => false],
            ['name' => ['en' => 'Solomon Islands Dollar', 'ar' => 'الدولار جزر سليمان'], 'code' => 'SBD', 'symbol' => 'SI$', 'description' => ['en' => 'Solomon Islands Dollar', 'ar' => 'الدولار جزر سليمان'], 'is_default' => false],
            ['name' => ['en' => 'Brunei Dollar', 'ar' => 'الدولار البروني'], 'code' => 'BND', 'symbol' => 'B$', 'description' => ['en' => 'Brunei Dollar', 'ar' => 'الدولار البروني'], 'is_default' => false],
            ['name' => ['en' => 'East Caribbean Dollar', 'ar' => 'الدولار الكاريبي الشرقي'], 'code' => 'XCD', 'symbol' => 'EC$', 'description' => ['en' => 'East Caribbean Dollar', 'ar' => 'الدولار الكاريبي الشرقي'], 'is_default' => false],
            ['name' => ['en' => 'Barbadian Dollar', 'ar' => 'الدولار البربادوسي'], 'code' => 'BBD', 'symbol' => 'Bds$', 'description' => ['en' => 'Barbadian Dollar', 'ar' => 'الدولار البربادوسي'], 'is_default' => false],
            ['name' => ['en' => 'Jamaican Dollar', 'ar' => 'الدولار الجامايكي'], 'code' => 'JMD', 'symbol' => 'J$', 'description' => ['en' => 'Jamaican Dollar', 'ar' => 'الدولار الجامايكي'], 'is_default' => false],
            ['name' => ['en' => 'Trinidad and Tobago Dollar', 'ar' => 'الدولار ترينيداد وتوباغو'], 'code' => 'TTD', 'symbol' => 'TT$', 'description' => ['en' => 'Trinidad and Tobago Dollar', 'ar' => 'الدولار ترينيداد وتوباغو'], 'is_default' => false],
            ['name' => ['en' => 'Bahamian Dollar', 'ar' => 'الدولار البهامي'], 'code' => 'BSD', 'symbol' => 'B$', 'description' => ['en' => 'Bahamian Dollar', 'ar' => 'الدولار البهامي'], 'is_default' => false],
            ['name' => ['en' => 'Belize Dollar', 'ar' => 'الدولار البليزي'], 'code' => 'BZD', 'symbol' => 'BZ$', 'description' => ['en' => 'Belize Dollar', 'ar' => 'الدولار البليزي'], 'is_default' => false],
            ['name' => ['en' => 'Costa Rican Colon', 'ar' => 'الكولون الكوستاريكي'], 'code' => 'CRC', 'symbol' => '₡', 'description' => ['en' => 'Costa Rican Colon', 'ar' => 'الكولون الكوستاريكي'], 'is_default' => false],
            ['name' => ['en' => 'Guatemalan Quetzal', 'ar' => 'الكيتزال الغواتيمالي'], 'code' => 'GTQ', 'symbol' => 'Q', 'description' => ['en' => 'Guatemalan Quetzal', 'ar' => 'الكيتزال الغواتيمالي'], 'is_default' => false],
            ['name' => ['en' => 'Honduran Lempira', 'ar' => 'اللمبيرا الهوندوراسي'], 'code' => 'HNL', 'symbol' => 'L', 'description' => ['en' => 'Honduran Lempira', 'ar' => 'اللمبيرا الهوندوراسي'], 'is_default' => false],
            ['name' => ['en' => 'Nicaraguan Cordoba', 'ar' => 'الكوردوبا النيكاراغوي'], 'code' => 'NIO', 'symbol' => 'C$', 'description' => ['en' => 'Nicaraguan Cordoba', 'ar' => 'الكوردوبا النيكاراغوي'], 'is_default' => false],
            ['name' => ['en' => 'Panamanian Balboa', 'ar' => 'البالبوا البنمي'], 'code' => 'PAB', 'symbol' => 'B/.', 'description' => ['en' => 'Panamanian Balboa', 'ar' => 'البالبوا البنمي'], 'is_default' => false],
            ['name' => ['en' => 'Dominican Peso', 'ar' => 'البيزو الدومينيكي'], 'code' => 'DOP', 'symbol' => 'RD$', 'description' => ['en' => 'Dominican Peso', 'ar' => 'البيزو الدومينيكي'], 'is_default' => false],
            ['name' => ['en' => 'Haitian Gourde', 'ar' => 'الجورد الهايتي'], 'code' => 'HTG', 'symbol' => 'G', 'description' => ['en' => 'Haitian Gourde', 'ar' => 'الجورد الهايتي'], 'is_default' => false],
            ['name' => ['en' => 'Cuban Peso', 'ar' => 'البيزو الكوبي'], 'code' => 'CUP', 'symbol' => '₱', 'description' => ['en' => 'Cuban Peso', 'ar' => 'البيزو الكوبي'], 'is_default' => false],
            ['name' => ['en' => 'Bolivian Boliviano', 'ar' => 'البوليفيانو البوليفي'], 'code' => 'BOB', 'symbol' => '$b', 'description' => ['en' => 'Bolivian Boliviano', 'ar' => 'البوليفيانو البوليفي'], 'is_default' => false],
            ['name' => ['en' => 'Paraguayan Guarani', 'ar' => 'الغواراني الباراغواياني'], 'code' => 'PYG', 'symbol' => 'Gs', 'description' => ['en' => 'Paraguayan Guarani', 'ar' => 'الغواراني الباراغواياني'], 'is_default' => false],
            ['name' => ['en' => 'Guyanese Dollar', 'ar' => 'الدولار الغياني'], 'code' => 'GYD', 'symbol' => 'G$', 'description' => ['en' => 'Guyanese Dollar', 'ar' => 'الدولار الغياني'], 'is_default' => false],
            ['name' => ['en' => 'Surinamese Dollar', 'ar' => 'الدولار السورينامي'], 'code' => 'SRD', 'symbol' => 'Sr$', 'description' => ['en' => 'Surinamese Dollar', 'ar' => 'الدولار السورينامي'], 'is_default' => false],
            ['name' => ['en' => 'Venezuelan Bolivar', 'ar' => 'البوليفار الفنزويلي'], 'code' => 'VES', 'symbol' => 'Bs.S', 'description' => ['en' => 'Venezuelan Bolivar', 'ar' => 'البوليفار الفنزويلي'], 'is_default' => false],
            ['name' => ['en' => 'Ecuadorian Sucre', 'ar' => 'السوكري الإكوادوري'], 'code' => 'ECS', 'symbol' => 'S/.', 'description' => ['en' => 'Ecuadorian Sucre', 'ar' => 'السوكري الإكوادوري'], 'is_default' => false],
        ];

        foreach ($currencies as $currency) {
            Currency::firstOrCreate(
                ['code' => $currency['code']],
                $currency
            );
        }
    }
}
