<?php

namespace App\Enum;

enum EmailTemplateName: string
{
    case INVOICE_CREATED = 'INVOICE_CREATED';
    case INVOICE_SENT = 'INVOICE_SENT';
    case JUDGE_CREATED = 'JUDGE_CREATED';
    case REGULATORY_BODY_CREATED = 'REGULATORY_BODY_CREATED';
    case TEAM_MEMBER_CREATED = 'TEAM_MEMBER_CREATED';
    case CASE_CREATED = 'CASE_CREATED';
    case HEARING_CREATED = 'HEARING_CREATED';
    case LICENSE_CREATED = 'LICENSE_CREATED';
    case COURT_CREATED = 'COURT_CREATED';
    case TASK_CREATED = 'TASK_CREATED';
    case CLE_RECORD_CREATED = 'CLE_RECORD_CREATED';
    case CLIENT_CREATED = 'CLIENT_CREATED';
}
