<?php

return [

    'available_currencies' => [
        ['name' => '{"en":"Tunisian Dinar","ar":"الدينار التونسي"}', 'code' => 'TND', 'symbol' => 'د.ت', 'description' => '{"en":"Tunisian Dinar","ar":"الدينار التونسي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Icelandic Krona","ar":"الكرونا الآيسلندية"}', 'code' => 'ISK', 'symbol' => 'kr', 'description' => '{"en":"Icelandic Krona","ar":"الكرونا الآيسلندية"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Pakistani Rupee","ar":"الروبية الباكستانية"}', 'code' => 'PKR', 'symbol' => '₨', 'description' => '{"en":"Pakistani Rupee","ar":"الروبية الباكستانية"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Lebanese Pound","ar":"الليرة اللبنانية"}', 'code' => 'LBP', 'symbol' => '£', 'description' => '{"en":"Lebanese Pound","ar":"الليرة اللبنانية"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Jordanian Dinar","ar":"الدينار الأردني"}', 'code' => 'JOD', 'symbol' => 'د.ا', 'description' => '{"en":"Jordanian Dinar","ar":"الدينار الأردني"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Omani Rial","ar":"الريال العماني"}', 'code' => 'OMR', 'symbol' => '﷼', 'description' => '{"en":"Omani Rial","ar":"الريال العماني"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Kuwaiti Dinar","ar":"الدينار الكويتي"}', 'code' => 'KWD', 'symbol' => 'د.ك', 'description' => '{"en":"Kuwaiti Dinar","ar":"الدينار الكويتي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Qatari Riyal","ar":"الريال القطري"}', 'code' => 'QAR', 'symbol' => '﷼', 'description' => '{"en":"Qatari Riyal","ar":"الريال القطري"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Saudi Riyal","ar":"الريال السعودي"}', 'code' => 'SAR', 'symbol' => '﷼', 'description' => '{"en":"Saudi Riyal","ar":"الريال السعودي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"UAE Dirham","ar":"الدرهم الإماراتي"}', 'code' => 'AED', 'symbol' => 'د.إ', 'description' => '{"en":"UAE Dirham","ar":"الدرهم الإماراتي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"US Dollar","ar":"الدولار الأمريكي"}', 'code' => 'USD', 'symbol' => '$', 'description' => '{"en":"United States Dollar","ar":"الدولار الأمريكي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Moroccan Dirham","ar":"الدرهم المغربي"}', 'code' => 'MAD', 'symbol' => 'DH', 'description' => '{"en":"Moroccan Dirham","ar":"الدرهم المغربي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Egyptian Pound","ar":"الجنيه المصري"}', 'code' => 'EGP', 'symbol' => '£', 'description' => '{"en":"Egyptian Pound","ar":"الجنيه المصري"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Russian Ruble","ar":"الروبل الروسي"}', 'code' => 'RUB', 'symbol' => '₽', 'description' => '{"en":"Russian Ruble","ar":"الروبل الروسي"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Turkish Lira","ar":"الليرة التركية"}', 'code' => 'TRY', 'symbol' => '₺', 'description' => '{"en":"Turkish Lira","ar":"الليرة التركية"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Chinese Yuan","ar":"اليوان الصيني"}', 'code' => 'CNY', 'symbol' => '¥', 'description' => '{"en":"Chinese Yuan","ar":"اليوان الصيني"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"British Pound","ar":"الجنيه الإسترليني"}', 'code' => 'GBP', 'symbol' => '£', 'description' => '{"en":"British Pound Sterling","ar":"الجنيه الإسترليني"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
        ['name' => '{"en":"Euro","ar":"اليورو"}', 'code' => 'EUR', 'symbol' => '€', 'description' => '{"en":"Euro","ar":"اليورو"}', 'created_by' => null, 'status' => true, 'created_at' => '2025-01-20 10:00', 'updated_at' => '2025-01-20 10:00'],
    ]
];
