<?php

return [
    // 'currency' => 'USD',
    // 'currency_symbol' => '$',
    'manual' => [
        'enabled' => env('PAYMENT_MANUAL_ENABLED', false),
        'name' => [
            'en' => 'Manual',
            'ar' => 'يدوي',
        ],
    ],
    'bank_transfer' => [
        'enabled' => env('PAYMENT_BANK_ENABLED', true),
        'name' => [
            'en' => 'Bank Transfer',
            'ar' => 'تحويل بنكي',
        ],
        'icon' => '🏦',
        'controller' => \App\Http\Controllers\BankPaymentController::class,
        'detail' => env('PAYMENT_BANK_DETAIL', "Bank: ICICI\nA/C No.: **************"),
    ],
    'stripe' => [
        'enabled' => env('PAYMENT_STRIPE_ENABLED', true),
        'name' => [
            'en' => 'Credit Card (Stripe)',
            'ar' => 'بطاقة ائتمان (Stripe)',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\StripePaymentController::class,
        'key' => env('PAYMENT_STRIPE_KEY', ''),
        'secret' => env('PAYMENT_STRIPE_SECRET', ''),
    ],
    'paypal' => [
        'enabled' => env('PAYMENT_PAYPAL_ENABLED', true),
        'name' => [
            'en' => 'PayPal',
            'ar' => 'باي بال',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PayPalPaymentController::class,
        'mode' => env('PAYMENT_PAYPAL_MODE', 'sandbox'),
        'client_id' => env('PAYMENT_PAYPAL_CLIENT_ID', 'Ad7xfQTPWKZAcZNDgKCYEL1W7NDfrV7JzV23Os_kqTVSy5_zzIPcL1-h3YRtfAJTkLraUwZwB77f4Dln'),
        'secret_key' => env('PAYMENT_PAYPAL_SECRET_KEY', 'EMGQOacnVfLAYsL6Fdfhtkp_ci5xnvQVZxxsBCBBTIOq6G_aqo9oVQvSFEYDIm5S5_z69Rb7Tl4UGIAu'),
    ],
    'razorpay' => [
        'enabled' => env('PAYMENT_RAZORPAY_ENABLED', false),
        'name' => [
            'en' => 'Razorpay',
            'ar' => 'رازورباي',
        ],
        'icon' => '💰',
        'controller' => \App\Http\Controllers\RazorpayController::class,
        'key' => env('PAYMENT_RAZORPAY_KEY', 'rzp_test_e8PsdGTRCf72A3'),
        'secret' => env('PAYMENT_RAZORPAY_SECRET', 'ICKMMeS7W9lDNZXz9PsCcHz8'),
    ],
    'mercadopago' => [
        'enabled' => env('PAYMENT_MERCADOPAGO_ENABLED', false),
        'name' => [
            'en' => 'Mercado Pago',
            'ar' => 'ميركادو باجو',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\MercadoPagoController::class,
        'mode' => env('PAYMENT_MERCADOPAGO_MODE', 'sandbox'),
        'access_token' => env('PAYMENT_MERCADOPAGO_ACCESS_TOKEN', 'APP_USR-3318506436823427-072403-4680217215b40298b02af56b22cbdc53-700671671'),
    ],
    'paystack' => [
        'enabled' => env('PAYMENT_PAYSTACK_ENABLED', false),
        'name' => [
            'en' => 'Paystack',
            'ar' => 'بايستاك',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PaystackPaymentController::class,
        'public_key' => env('PAYMENT_PAYSTACK_PUBLIC_KEY', 'pk_test_9f6aaad1da032c2081934aa6cf8518d94a308b99'),
        'secret_key' => env('PAYMENT_PAYSTACK_SECRET_KEY', 'sk_test_90ed83442cfdefca663b0ee1e9c9f8189d675f6b'),
    ],
    'flutterwave' => [
        'enabled' => env('PAYMENT_FLUTTERWAVE_ENABLED', false),
        'name' => [
            'en' => 'Flutterwave',
            'ar' => 'فلاترويف',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\FlutterwavePaymentController::class,
        'public_key' => env('PAYMENT_FLUTTERWAVE_PUBLIC_KEY', 'FLWPUBK_TEST-05113ace39b840b31bcd365f532858ca-X'),
        'secret_key' => env('PAYMENT_FLUTTERWAVE_SECRET_KEY', 'FLWSECK_TEST-b08c1c32a710451237c2372b5bafbeea-X'),
    ],
    'paytabs' => [
        'enabled' => env('PAYMENT_PAYTABS_ENABLED', true),
        'name' => [
            'en' => 'Paytabs',
            'ar' => 'بايتابس',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PayTabsPaymentController::class,
        'profile_id' => env('PAYMENT_PAYTABS_PROFILE_ID', '123985'),
        'server_key' => env('PAYMENT_PAYTABS_SERVER_KEY', 'SNJ9LG9RBG-J69HGL6BJ2-B9KWDTRTN2'),
        'region' => env('PAYMENT_PAYTABS_REGION', 'ARE'),
        'mode' => env('PAYMENT_PAYTABS_MODE', 'sandbox'),
    ],
    'skrill' => [
        'enabled' => env('PAYMENT_SKRILL_ENABLED', false),
        'name' => [
            'en' => 'Skrill',
            'ar' => 'سكريل',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\SkrillPaymentController::class,
        'merchant_id' => env('PAYMENT_SKRILL_MERCHANT_ID', 'skrill_user_test2@smart2pay.com'),
        'secret_word' => env('PAYMENT_SKRILL_SECRET_WORD', 'Qazxsw21.s2p!'),
    ],
    'coingate' => [
        'enabled' => env('PAYMENT_COINGATE_ENABLED', false),
        'name' => [
            'en' => 'Coin Gate',
            'ar' => 'كوين جيت',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\CoinGatePaymentController::class,
        'api_token' => env('PAYMENT_COINGATE_API_TOKEN', 'n6cjiN4w5p_s3ayK9zAkA3tasRUaQ3mfosx52BpT'),
        'mode' => env('PAYMENT_COINGATE_MODE', 'sandbox'),
    ],
    'payfast' => [
        'enabled' => env('PAYMENT_PAYFAST_ENABLED', false),
        'name' => [
            'en' => 'Pay Fast',
            'ar' => 'باي فاست',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PayfastPaymentController::class,
        'merchant_id' => env('PAYMENT_PAYFAST_MERCHANT_ID', '10029177'),
        'merchant_key' => env('PAYMENT_PAYFAST_MERCHANT_KEY', 'p4ktujv6gen32'),
        'passphrase' => env('PAYMENT_PAYFAST_PASSPHRASE', 'rajodiyapayfast'),
        'mode' => env('PAYMENT_PAYFAST_MODE', 'sandbox'),
    ],
    'tap' => [
        'enabled' => env('PAYMENT_TAP_ENABLED', true),
        'name' => [
            'en' => 'Tap',
            'ar' => 'تاب',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\TapPaymentController::class,
        'secret_key' => env('PAYMENT_TAP_SECRET_KEY', ''),
    ],
    'xendit' => [
        'enabled' => env('PAYMENT_XENDIT_ENABLED', false),
        'name' => [
            'en' => 'Xendit',
            'ar' => 'زينديت',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\XenditPaymentController::class,
        'api_key' => env('PAYMENT_XENDIT_API_KEY', 'xnd_development_2ADaRSmN4LzAvXF6QzC2NgqeOdJnIeMB14nCJNUZTbGa2IKPUMCTBgXEP7bjX'),
    ],
    'paytr' => [
        'enabled' => env('PAYMENT_PAYTR_ENABLED', false),
        'name' => [
            'en' => 'PayTR',
            'ar' => 'باي تي آر',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PayTRPaymentController::class,
        'merchant_id' => env('PAYMENT_PAYTR_MERCHANT_ID', '369665'),
        'merchant_key' => env('PAYMENT_PAYTR_MERCHANT_KEY', '5o7dH6ySGNSnU3ui'),
        'merchant_salt' => env('PAYMENT_PAYTR_MERCHANT_SALT', 'k8Z93ao1cJ1NUjTM'),
    ],
    'mollie' => [
        'enabled' => env('PAYMENT_MOLLIE_ENABLED', false),
        'name' => [
            'en' => 'Mollie',
            'ar' => 'مولي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\MolliePaymentController::class,
        'api_key' => env('PAYMENT_MOLLIE_API_KEY', 'test_drRNWfgDpRz43qxJ2VG6VSgW8Nzq5H'),
    ],
    'toyyibpay' => [
        'enabled' => env('PAYMENT_TOYYIBPAY_ENABLED', false),
        'name' => [
            'en' => 'Toyyib Pay',
            'ar' => 'طيب باي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\ToyyibPayPaymentController::class,
        'category_code' => env('PAYMENT_TOYYIBPAY_CATEGORY_CODE', 'luwaaf3e'),
        'secret_key' => env('PAYMENT_TOYYIBPAY_SECRET_KEY', 'sop4ikpj-1qrg-i4lv-xb3z-0j5p81rn55in'),
    ],
    'cashfree' => [
        'enabled' => env('PAYMENT_CASHFREE_ENABLED', false),
        'name' => [
            'en' => 'Cashfree',
            'ar' => 'كاش فري',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\CashfreeController::class,
        'mode' => env('PAYMENT_CASHFREE_MODE', 'sandbox'),
        'secret_key' => env('PAYMENT_CASHFREE_SECRET_KEY', ''),
        'public_key' => env('PAYMENT_CASHFREE_PUBLIC_KEY', 'TEST103872709ceb85b1602c29cc31b107278301'),
    ],
    'iyzipay' => [
        'enabled' => env('PAYMENT_IYZIPAY_ENABLED', false),
        'name' => [
            'en' => 'Iyzipay',
            'ar' => 'إيزي باي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\IyzipayPaymentController::class,
        'mode' => env('PAYMENT_IYZIPAY_MODE', 'sandbox'),
        'secret_key' => env('PAYMENT_IYZIPAY_SECRET_KEY', 'sandbox-41KGyTBIn3yw24tH9WOAI9LeexWdV0Fo'),
        'public_key' => env('PAYMENT_IYZIPAY_PUBLIC_KEY', 'sandbox-vpWI8D8A8cIdrDtzGETfPEOm3huNb33U'),
    ],
    'benefit' => [
        'enabled' => env('PAYMENT_BENEFIT_ENABLED', false),
        'name' => [
            'en' => 'Benefit',
            'ar' => 'بينيفت',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\BenefitPaymentController::class,
        'mode' => env('PAYMENT_BENEFIT_MODE', 'sandbox'),
        'secret_key' => env('PAYMENT_BENEFIT_SECRET_KEY', ''),
        'public_key' => env('PAYMENT_BENEFIT_PUBLIC_KEY', 'pk_test_4g6LtBAFExwsb9ecjJDfXiYV'),
    ],
    'ozow' => [
        'enabled' => env('PAYMENT_OZOW_ENABLED', false),
        'name' => [
            'en' => 'Ozow',
            'ar' => 'أوزو',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\OzowPaymentController::class,
        'mode' => env('PAYMENT_OZOW_MODE', 'sandbox'),
        'site_key' => env('PAYMENT_OZOW_SITE_KEY', 'WEN-WEN-003'),
        'private_key' => env('PAYMENT_OZOW_PRIVATE_KEY', '5ijH5VKlpmjHdxMGwUvkA8ivhEB5w5Xf'),
        'api_key' => env('PAYMENT_OZOW_API_KEY', 'lXNzCh0DpZBfpcid5fLldcss76Uv3PNM'),
    ],
    'easebuzz' => [
        'enabled' => env('PAYMENT_EASEBUZZ_ENABLED', false),
        'name' => [
            'en' => 'Easebuzz',
            'ar' => 'إيزبز',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\EasebuzzPaymentController::class,
        'merchant_key' => env('PAYMENT_EASEBUZZ_MERCHANT_KEY', 'G4AR9WUW1'),
        'salt_key' => env('PAYMENT_EASEBUZZ_SALT_KEY', 'ULPY6UW38'),
        'environment' => env('PAYMENT_EASEBUZZ_ENVIRONMENT', 'demo'),
    ],
    'khalti' => [
        'enabled' => env('PAYMENT_KHALTI_ENABLED', false),
        'name' => [
            'en' => 'Khalti',
            'ar' => 'خالتي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\KhaltiPaymentController::class,
        'secret_key' => env('PAYMENT_KHALTI_SECRET_KEY', 'test_secret_key_2f4ce233c9fe4db299cb3ff461028e51'),
        'public_key' => env('PAYMENT_KHALTI_PUBLIC_KEY', 'test_public_key_d7a1edf24fbd47219865fc3c4586888b'),
    ],
    'authorizenet' => [
        'enabled' => env('PAYMENT_AUTHORIZENET_ENABLED', false),
        'name' => [
            'en' => 'Authorize.net',
            'ar' => 'أوثورايز.نت',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\AuthorizeNetPaymentController::class,
        'mode' => env('PAYMENT_AUTHORIZENET_MODE', 'sandbox'),
        'merchant_id' => env('PAYMENT_AUTHORIZENET_MERCHANT_ID', '635Q6ftmE27'),
        'transaction_key' => env('PAYMENT_AUTHORIZENET_TRANSACTION_KEY', '92G6j97CV23JsWrk'),
    ],
    'fedapay' => [
        'enabled' => env('PAYMENT_FEDAPAY_ENABLED', false),
        'name' => [
            'en' => 'Fedapay',
            'ar' => 'فيداباي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\FedaPayPaymentController::class,
        'mode' => env('PAYMENT_FEDAPAY_MODE', 'sandbox'),
        'secret_key' => env('PAYMENT_FEDAPAY_SECRET_KEY', 'sk_sandbox_D7UaHvIWputPlilghOg7Hxre'),
        'public_key' => env('PAYMENT_FEDAPAY_PUBLIC_KEY', 'pk_sandbox_rcO3DdlKATFe-2h4NhJBhQHt'),
    ],
    'payhere' => [
        'enabled' => env('PAYMENT_PAYHERE_ENABLED', false),
        'name' => [
            'en' => 'Pay Here',
            'ar' => 'باي هير',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PayHerePaymentController::class,
        'mode' => env('PAYMENT_PAYHERE_MODE', 'sandbox'),
        'merchant_id' => env('PAYMENT_PAYHERE_MERCHANT_ID', '1223903'),
        'merchant_secret' => env('PAYMENT_PAYHERE_MERCHANT_SECRET', 'MTY4MTQwNjY1ODM1MTE4NDA5NTA1ODQxOTE0OTEzMTA4MTAzMTQ5'),
        'app_id' => env('PAYMENT_PAYHERE_APP_ID', '4OVxgDxWLuy4JDDSparOo43H7'),
        'app_secret' => env('PAYMENT_PAYHERE_APP_SECRET', '8gfC8Lr42eU8m4OJAJDybB4UpsygCEQa74Tv9DVHSehT'),
    ],
    'cinetpay' => [
        'enabled' => env('PAYMENT_CINETPAY_ENABLED', false),
        'name' => [
            'en' => 'Cinet Pay',
            'ar' => 'سيني باي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\CinetPayPaymentController::class,
        'site_id' => env('PAYMENT_CINETPAY_SITE_ID', '932948'),
        'api_key' => env('PAYMENT_CINETPAY_API_KEY', '875761857625ea7da46f407.47059526'),
        'secret_key' => env('PAYMENT_CINETPAY_SECRET_KEY', '1883168137625ea9026fb3b5.72705402'),
    ],
    'paiement' => [
        'enabled' => env('PAYMENT_PAIEMENT_ENABLED', false),
        'name' => [
            'en' => 'Paiement Pro',
            'ar' => 'بايمنت برو',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PaiementPaymentController::class,
        'merchant_id' => env('PAYMENT_PAIEMENT_MERCHANT_ID', 'PP-F258'),
    ],
    'paymentwall' => [
        'enabled' => env('PAYMENT_PAYMENTWALL_ENABLED', false),
        'name' => [
            'en' => 'Payment Wall',
            'ar' => 'بيمنت وول',
        ],
        'icon' => '🅿️',
        'controller' => \App\Http\Controllers\PaymentWallPaymentController::class,
        'public_key' => env('PAYMENT_PAYMENTWALL_PUBLIC_KEY', 't_365891948ea844de751301cbcc1897'),
        'private_key' => env('PAYMENT_PAYMENTWALL_PRIVATE_KEY', 't_365891948ea844de751301cbcc1897'),
    ],
    'sspay' => [
        'enabled' => env('PAYMENT_SSPAY_ENABLED', false),
        'name' => [
            'en' => 'SS Pay',
            'ar' => 'إس إس باي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\SSPayPaymentController::class,
        'secret_key' => env('PAYMENT_SSPAY_SECRET_KEY', 'gkxfw65k-saic-ccl7-unf2-noto3phisl7i'),
        'category_code' => env('PAYMENT_SSPAY_CATEGORY_CODE', 'lnpbm6ei'),
    ],
    'yookassa' => [
        'enabled' => env('PAYMENT_YOOKASSA_ENABLED', false),
        'name' => [
            'en' => 'Yoo Kassa',
            'ar' => 'يو كاسا',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\YooKassaPaymentController::class,
        'shop_id' => env('PAYMENT_YOOKASSA_SHOP_ID', '900839'),
        'secret_key' => env('PAYMENT_YOOKASSA_SECRET_KEY', 'test_hN6Bgz7yc-f_DhUfKjNEp28bBd1g3LAubegbgijstpw'),
    ],
    'aamarpay' => [
        'enabled' => env('PAYMENT_AAMARPAY_ENABLED', false),
        'name' => [
            'en' => 'Aamar Pay',
            'ar' => 'أمار باي',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\AamarpayPaymentController::class,
        'store_id' => env('PAYMENT_AAMARPAY_STORE_ID', 'aamarpaytest'),
        'signature' => env('PAYMENT_AAMARPAY_SIGNATURE', 'dbb74894e82415a2f7ff0ec3a97e4183'),
        'mode' => env('PAYMENT_AAMARPAY_MODE', 'sandbox'),
    ],
    'midtrans' => [
        'enabled' => env('PAYMENT_MIDTRANS_ENABLED', false),
        'name' => [
            'en' => 'Midtrans',
            'ar' => 'ميدترانس',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\MidtransPaymentController::class,
        'mode' => env('PAYMENT_MIDTRANS_MODE', 'sandbox'),
        'secret_key' => env('PAYMENT_MIDTRANS_SECRET_KEY', 'SB-Mid-server-CkuriL9PLmx6NQwXjqTMXEXG'),
    ],
    'nepalste' => [
        'enabled' => env('PAYMENT_NEPALSTE_ENABLED', false),
        'name' => [
            'en' => 'Nepalste',
            'ar' => 'نيبالست',
        ],
        'icon' => '💳',
        'controller' => \App\Http\Controllers\NepalstePaymentController::class,
        'mode' => env('PAYMENT_NEPALSTE_MODE', 'sandbox'),
        'secret_key' => env('PAYMENT_NEPALSTE_SECRET_KEY', ''),
        'public_key' => env('PAYMENT_NEPALSTE_PUBLIC_KEY', ''),
    ],
];
