<?php

return [
    'UTC' => 'UTC',
    'Africa/Casablanca' => '(GMT+0:00) Africa/Casablanca (Western European Time)',
    'Africa/Algiers' => '(GMT+1:00) Africa/Algiers (Central European Time)',
    'Africa/Tunis' => '(GMT+1:00) Africa/Tunis (Central European Time)',
    'Africa/Cairo' => '(GMT+2:00) Africa/Cairo (Eastern European Time)',
    'Asia/Amman' => '(GMT+2:00) Asia/Amman (Eastern European Time)',
    'Asia/Beirut' => '(GMT+2:00) Asia/Beirut (Eastern European Time)',
    'Asia/Damascus' => '(GMT+2:00) Asia/Damascus (Eastern European Time)',
    'Asia/Gaza' => '(GMT+2:00) Asia/Gaza (Eastern European Time)',
    'Asia/Istanbul' => '(GMT+2:00) Asia/Istanbul (Eastern European Time)',
    'Asia/Jerusalem' => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)',
    'Africa/Dar_es_Salaam' => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)',
    'Africa/Djibouti' => '(GMT+3:00) Africa/Djibouti (Eastern African Time)',
    'Africa/Khartoum' => '(GMT+3:00) Africa/Khartoum (Eastern African Time)',
    'Africa/Mogadishu' => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)',
    'Asia/Aden' => '(GMT+3:00) Asia/Aden (Arabia Standard Time)',
    'Asia/Baghdad' => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)',
    'Asia/Bahrain' => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)',
    'Asia/Riyadh' => '(GMT+3:00) Asia/Riyadh (Arabia Standard Time)',
    'Asia/Kuwait' => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)',
    'Asia/Qatar' => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)',
    'Indian/Comoro' => '(GMT+3:00) Indian/Comoro (Eastern African Time)',
    'Asia/Tehran' => '(GMT+3:30) Asia/Tehran (Iran Standard Time)',
    'Asia/Dubai' => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)',
    'Asia/Muscat' => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)',
];
